services:
  - type: web
    name: banco-questoes-mvp-5
    env: python
    buildCommand: |
      # Instalar dependências do backend
      pip install -r requirements.txt
      
      # Instalar Node.js e pnpm
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      sudo apt-get install -y nodejs
      npm install -g pnpm
      
      # Instalar dependências do frontend
      cd frontend
      pnpm install
      
      # Build do frontend
      pnpm run build
      
      # Copiar arquivos buildados para o diretório static do Flask
      cp -r dist/* ../src/static/
      
      # Voltar para o diretório raiz
      cd ..
    startCommand: python src/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000

